# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

ui-chrome-tests: &ui-chrome-tests
  name: 'UI Tests - Chrome'
  caches:
    - cypress
    - node
  script:
    - npx cypress run --record --key 0e92a938-6e98-47df-a5ad-96d80927613f

pipelines:
  default:
    - step:
        name: Install dependencies and build frontend application
        caches:
          - yarn
          - cypress
          - node
  script:
    - yarn add cypress
