image: atlassian/default-image:2

pipelines:
  default:
      - step:
          name: 'Instalar dependencias'
          script:
            - yarn add cypress
      - step:
          name: 'Run Cypress Testing'
          script:
            - npx cypress run --record --key a321bdc6-24e5-4032-b465-05cbe221aa9e