image: cypress/browsers:node14.17.0-chrome88-ff89
pipelines:
  default:
    - step:
        name: Instalar dependencias
        caches:
          - yarn
          - cypress
          - node
        script:
          - yarn install cypress
        artifacts:
          - build/**

     - step:
        name: Run Cypress Testing
        script:
          - yarn run cypress run --record --key a321bdc6-24e5-4032-b465-05cbe221aa9e

definitions:
  caches:
    yarn: $HOME/.cache
    cypress: $HOME/.cache/Cypress
