import { Moment } from "moment";

export interface LandingBlock {
	index:   number;
	key:     string;
	name:    string;
	label?:  string;
	status:  boolean;
}

export interface Alias {
	[key : string] : string 
}
// Generated by https://quicktype.io

export interface ConfigCountdown {
	date:          Moment;
	messageIn:     string;
	messageFinish: string;
}

export interface PropsDrawer {
	visibleDrawer : boolean
	setVisibleDrawer : React.Dispatch<React.SetStateAction<boolean>>
}
export interface DataSource {
	created_at: 			string;
	event_id: 				string;
	updated_id: 			string;
	_id: 					string;
	main_landing_blocks: 	LandingBlock[];
}


export interface Speaker {
	_id:                  string;
	name:                 string;
	image:                string;
	description_activity: boolean;
	profession:           string;
	published:            boolean;
	order:                number;
	index:                number;
	event_id:             string;
	updated_at:           string;
	created_at:           string;
}

export interface SectionDescription {
	data:  Description[];
	links: Links;
	meta:  Meta;
}

export interface Description {
	_id:        string;
	type:       string;
	value:      string;
	index:      number;
	event_id:   string;
	updated_at: string;
	created_at: string;
}

export interface Links {
	first: string;
	last:  string;
	prev:  null;
	next:  null;
}

export interface Meta {
	current_page: number;
	from:         number;
	last_page:    number;
	path:         string;
	per_page:     number;
	to:           number;
	total:        number;
}


export interface Agenda {
	_id:                     string;
	name:                    string;
	image:                   string;
	description:             string;
	capacity:                number;
	event_id:                string;
	datetime_end:            string;
	datetime_start:          string;
	date_start_zoom:         string;
	date_end_zoom:           string;
	hosts:					 any[];
	host_ids:				 any[];
	updated_at:              string;
	created_at:              string;
	type_id:                 string;
	requires_registration:   boolean; 
	type:                    any;
	transmition:             string;
	tabs:                    Tabs;
	avalibleGames:           AvalibleGame[];
	habilitar_ingreso:       string;
	isPublished:             boolean;

}

export interface AvalibleGame {
	name:     string;
	id:       string;
	index:    number;
	showGame: boolean;
	picture:  string;
}

export interface Tabs {
	chat:      boolean;
	surveys:   boolean;
	attendees: boolean;
	games:     boolean;
}
export interface Sponsor {
	short_description: string;
	name:              string;
	stand_image:       string;
	telefono:          string;
	index:             number;
	services:          any[];
	times_and_venues:  string;
	description:       string;
	gallery:           Gallery[];
	video_url:         string;
	stand_type:        string;
	brochure:          string;
	social_networks:   any[];
	contact_info:      ContactInfo;
	list_image:        string;
	visitors_space_id: string;
	email:             string;
	visible:           boolean;
	webpage:           string;
	advisor:           any[];
	id:                string;
}

export interface ContactInfo {
	description: string;
	image:       string;
}

export interface Gallery {
	image: string;
}
