export interface IObserver {
    id : string
    label: string;
    value : string;
}


export interface CreateObservers {
    data : string[]
}


export enum TypeCalendarView {
    day = "day", 
    week = "week", 
    month ="month", 
    agenda ="agenda"
}

// Generated by https://quicktype.io


export interface ITypeMeenting {
    id : string
    nameType : string 
    style : string
}
export interface IColor {
    hsl:    Hsl;
    hex:    string;
    rgb:    RGB;
    hsv:    Hsl;
    oldHue: number;
    source: string;
}

export interface Hsl {
    h:  number;
    s:  number;
    l?: number;
    a:  number;
    v?: number;
}

export interface RGB {
    r: number;
    g: number;
    b: number;
    a: number;
}
