let cityOptions = [
  { label: 'Abejorral' },
  { label: 'Abrego' },
  { label: 'Abriaquí' },
  { label: 'Acacías' },
  { label: 'Acandí' },
  { label: 'Acevedo' },
  { label: 'Achí' },
  { label: 'Agrado' },
  { label: 'Agua de Dios' },
  { label: 'Aguachica' },
  { label: 'Aguada' },
  { label: 'Aguadas' },
  { label: 'Aguazul' },
  { label: 'Agustín Codazzi' },
  { label: 'Aipe' },
  { label: 'Albania' },
  { label: 'Albán' },
  { label: 'Alcalá' },
  { label: 'Aldana' },
  { label: 'Alejandría' },
  { label: 'Algarrobo' },
  { label: 'Algeciras' },
  { label: 'Almaguer' },
  { label: 'Almeida' },
  { label: 'Alpujarra' },
  { label: 'Altamira' },
  { label: 'Alto Baudó' },
  { label: 'Altos del Rosario' },
  { label: 'Alvarado' },
  { label: 'Amagá' },
  { label: 'Amalfi' },
  { label: 'Ambalema' },
  { label: 'Anapoima' },
  { label: 'Ancuyá' },
  { label: 'Andalucía' },
  { label: 'Andes' },
  { label: 'Angelópolis' },
  { label: 'Angostura' },
  { label: 'Anolaima' },
  { label: 'Anorí' },
  { label: 'Anserma' },
  { label: 'Ansermanuevo' },
  { label: 'Anza' },
  { label: 'Anzoátegui' },
  { label: 'Apartadó' },
  { label: 'Apulo' },
  { label: 'Apía' },
  { label: 'Aquitania' },
  { label: 'Aracataca' },
  { label: 'Aranzazu' },
  { label: 'Aratoca' },
  { label: 'Arauca' },
  { label: 'Arauquita' },
  { label: 'Arbeláez' },
  { label: 'Arboleda' },
  { label: 'Arboledas' },
  { label: 'Arboletes' },
  { label: 'Arcabuco' },
  { label: 'Arenal' },
  { label: 'Argelia' },
  { label: 'Ariguaní' },
  { label: 'Arjona' },
  { label: 'Armenia' },
  { label: 'Armero' },
  { label: 'Arroyohondo' },
  { label: 'Astrea' },
  { label: 'Ataco' },
  { label: 'Atrato' },
  { label: 'Ayapel' },
  { label: 'Bagadó' },
  { label: 'Bahía Solano' },
  { label: 'Bajo Baudó' },
  { label: 'Balboa' },
  { label: 'Baranoa' },
  { label: 'Baraya' },
  { label: 'Barbacoas' },
  { label: 'Barbosa' },
  { label: 'Barichara' },
  { label: 'Barranca de Upía' },
  { label: 'Barrancabermeja' },
  { label: 'Barrancas' },
  { label: 'Barranco Minas' },
  { label: 'Barranco de Loba' },
  { label: 'Barranquilla' },
  { label: 'Becerril' },
  { label: 'Belalcázar' },
  { label: 'Bello' },
  { label: 'Belmira' },
  { label: 'Beltrán' },
  { label: 'Belén' },
  { label: 'Belén de Bajirá' },
  { label: 'Belén de Los Andaquies' },
  { label: 'Belén de Umbría' },
  { label: 'Berbeo' },
  { label: 'Betania' },
  { label: 'Betulia' },
  { label: 'Betéitiva' },
  { label: 'Bituima' },
  { label: 'Boavita' },
  { label: 'Bochalema' },
  { label: 'Bogotá' },
  { label: 'Bojacá' },
  { label: 'Bojaya' },
  { label: 'Bolívar' },
  { label: 'Bosconia' },
  { label: 'Boyacá' },
  { label: 'Briceño' },
  { label: 'Bucaramanga' },
  { label: 'Bucarasica' },
  { label: 'Buenaventura' },
  { label: 'Buenavista' },
  { label: 'Buenos Aires' },
  { label: 'Buesaco' },
  { label: 'Bugalagrande' },
  { label: 'Buriticá' },
  { label: 'Busbanzá' },
  { label: 'Cabrera' },
  { label: 'Cabuyaro' },
  { label: 'Cacahual' },
  { label: 'Cachipay' },
  { label: 'Cachirá' },
  { label: 'Caicedo' },
  { label: 'Caicedonia' },
  { label: 'Caimito' },
  { label: 'Cajamarca' },
  { label: 'Cajibío' },
  { label: 'Cajicá' },
  { label: 'Calamar' },
  { label: 'Calarcá' },
  { label: 'Caldas' },
  { label: 'Caldono' },
  { label: 'Cali' },
  { label: 'California' },
  { label: 'Calima' },
  { label: 'Caloto' },
  { label: 'Campamento' },
  { label: 'Campo de La Cruz' },
  { label: 'Campoalegre' },
  { label: 'Campohermoso' },
  { label: 'Canalete' },
  { label: 'Candelaria' },
  { label: 'Cantagallo' },
  { label: 'Caparrapí' },
  { label: 'Capitanejo' },
  { label: 'Caqueza' },
  { label: 'Caracolí' },
  { label: 'Caramanta' },
  { label: 'Carcasí' },
  { label: 'Carepa' },
  { label: 'Carmen de Apicalá' },
  { label: 'Carmen de Bolívar' },
  { label: 'Carmen de Carupa' },
  { label: 'Carmen del Atrato' },
  { label: 'Carmen del Darien' },
  { label: 'Carolina' },
  { label: 'Cartagena' },
  { label: 'Cartagena del Chairá' },
  { label: 'Cartago' },
  { label: 'Caruru' },
  { label: 'Casabianca' },
  { label: 'Castilla la Nueva' },
  { label: 'Caucasia' },
  { label: 'Cañasgordas' },
  { label: 'Cepitá' },
  { label: 'Cereté' },
  { label: 'Cerinza' },
  { label: 'Cerrito' },
  { label: 'Cerro San Antonio' },
  { label: 'Chachagüí' },
  { label: 'Chaguaní' },
  { label: 'Chalán' },
  { label: 'Chameza' },
  { label: 'Chaparral' },
  { label: 'Charalá' },
  { label: 'Charta' },
  { label: 'Chibolo' },
  { label: 'Chigorodó' },
  { label: 'Chima' },
  { label: 'Chimichagua' },
  { label: 'Chimá' },
  { label: 'Chinavita' },
  { label: 'Chinchiná' },
  { label: 'Chinácota' },
  { label: 'Chinú' },
  { label: 'Chipaque' },
  { label: 'Chipatá' },
  { label: 'Chiquinquirá' },
  { label: 'Chiriguaná' },
  { label: 'Chiscas' },
  { label: 'Chita' },
  { label: 'Chitagá' },
  { label: 'Chitaraque' },
  { label: 'Chivatá' },
  { label: 'Chivor' },
  { label: 'Choachí' },
  { label: 'Chocontá' },
  { label: 'Chía' },
  { label: 'Chíquiza' },
  { label: 'Cicuco' },
  { label: 'Cimitarra' },
  { label: 'Circasia' },
  { label: 'Cisneros' },
  { label: 'Ciudad Bolívar' },
  { label: 'Ciénaga' },
  { label: 'Ciénaga de Oro' },
  { label: 'Ciénega' },
  { label: 'Clemencia' },
  { label: 'Cocorná' },
  { label: 'Coello' },
  { label: 'Cogua' },
  { label: 'Colombia' },
  { label: 'Coloso' },
  { label: 'Colón' },
  { label: 'Concepción' },
  { label: 'Concordia' },
  { label: 'Condoto' },
  { label: 'Confines' },
  { label: 'Consaca' },
  { label: 'Contadero' },
  { label: 'Contratación' },
  { label: 'Convención' },
  { label: 'Copacabana' },
  { label: 'Coper' },
  { label: 'Corinto' },
  { label: 'Coromoro' },
  { label: 'Corozal' },
  { label: 'Corrales' },
  { label: 'Cota' },
  { label: 'Cotorra' },
  { label: 'Covarachía' },
  { label: 'Coveñas' },
  { label: 'Coyaima' },
  { label: 'Cravo Norte' },
  { label: 'Cuaspud' },
  { label: 'Cubarral' },
  { label: 'Cubará' },
  { label: 'Cucaita' },
  { label: 'Cucunubá' },
  { label: 'Cucutilla' },
  { label: 'Cumaral' },
  { label: 'Cumaribo' },
  { label: 'Cumbal' },
  { label: 'Cumbitara' },
  { label: 'Cunday' },
  { label: 'Curillo' },
  { label: 'Curití' },
  { label: 'Curumaní' },
  { label: 'Cuítiva' },
  { label: 'Cáceres' },
  { label: 'Cácota' },
  { label: 'Cértegui' },
  { label: 'Cómbita' },
  { label: 'Córdoba' },
  { label: 'Cúcuta' },
  { label: 'Dabeiba' },
  { label: 'Dagua' },
  { label: 'Dibulla' },
  { label: 'Distracción' },
  { label: 'Dolores' },
  { label: 'Don Matías' },
  { label: 'Dosquebradas' },
  { label: 'Duitama' },
  { label: 'Duranía' },
  { label: 'Ebéjico' },
  { label: 'El Bagre' },
  { label: 'El Banco' },
  { label: 'El Cairo' },
  { label: 'El Calvario' },
  { label: 'El Cantón del San Pablo' },
  { label: 'El Carmen' },
  { label: 'El Carmen de Chucurí' },
  { label: 'El Carmen de Viboral' },
  { label: 'El Castillo' },
  { label: 'El Cerrito' },
  { label: 'El Charco' },
  { label: 'El Cocuy' },
  { label: 'El Colegio' },
  { label: 'El Copey' },
  { label: 'El Doncello' },
  { label: 'El Dorado' },
  { label: 'El Dovio' },
  { label: 'El Encanto' },
  { label: 'El Espino' },
  { label: 'El Guacamayo' },
  { label: 'El Guamo' },
  { label: 'El Molino' },
  { label: 'El Paso' },
  { label: 'El Paujil' },
  { label: 'El Peñol' },
  { label: 'El Peñón' },
  { label: 'El Pital' },
  { label: 'El Piñon' },
  { label: 'El Playón' },
  { label: 'El Retorno' },
  { label: 'El Retén' },
  { label: 'El Roble' },
  { label: 'El Rosal' },
  { label: 'El Rosario' },
  { label: 'El Santuario' },
  { label: 'El Tablón de Gómez' },
  { label: 'El Tambo' },
  { label: 'El Tarra' },
  { label: 'El Zulia' },
  { label: 'El Águila' },
  { label: 'Elías' },
  { label: 'Encino' },
  { label: 'Enciso' },
  { label: 'Entrerrios' },
  { label: 'Envigado' },
  { label: 'Espinal' },
  { label: 'Facatativá' },
  { label: 'Falan' },
  { label: 'Filadelfia' },
  { label: 'Filandia' },
  { label: 'Firavitoba' },
  { label: 'Flandes' },
  { label: 'Florencia' },
  { label: 'Floresta' },
  { label: 'Florida' },
  { label: 'Floridablanca' },
  { label: 'Florián' },
  { label: 'Fonseca' },
  { label: 'Fortul' },
  { label: 'Fosca' },
  { label: 'Francisco Pizarro' },
  { label: 'Fredonia' },
  { label: 'Fresno' },
  { label: 'Frontino' },
  { label: 'Fuente de oro' },
  { label: 'Fundación' },
  { label: 'Funes' },
  { label: 'Funza' },
  { label: 'Fusagasugá' },
  { label: 'Fómeque' },
  { label: 'Fúquene' },
  { label: 'Gachalá' },
  { label: 'Gachancipá' },
  { label: 'Gachantivá' },
  { label: 'Gachetá' },
  { label: 'Galapa' },
  { label: 'Galeras' },
  { label: 'Galán' },
  { label: 'Gama' },
  { label: 'Gamarra' },
  { label: 'Gambita' },
  { label: 'Garagoa' },
  { label: 'Garzón' },
  { label: 'Gigante' },
  { label: 'Ginebra' },
  { label: 'Giraldo' },
  { label: 'Girardot' },
  { label: 'Girardota' },
  { label: 'González' },
  { label: 'Gramalote' },
  { label: 'Granada' },
  { label: 'Guaca' },
  { label: 'Guacamayas' },
  { label: 'Guacarí' },
  { label: 'Guachetá' },
  { label: 'Guachucal' },
  { label: 'Guadalajara de Buga' },
  { label: 'Guadalupe' },
  { label: 'Guaduas' },
  { label: 'Guaitarilla' },
  { label: 'Gualmatán' },
  { label: 'Guamal' },
  { label: 'Guamo' },
  { label: 'Guapi' },
  { label: 'Guapotá' },
  { label: 'Guaranda' },
  { label: 'Guarne' },
  { label: 'Guasca' },
  { label: 'Guatapé' },
  { label: 'Guataquí' },
  { label: 'Guatavita' },
  { label: 'Guateque' },
  { label: 'Guavatá' },
  { label: 'Guayabal de Siquima' },
  { label: 'Guayabetal' },
  { label: 'Guayatá' },
  { label: 'Gutiérrez' },
  { label: 'Guática' },
  { label: 'Gámeza' },
  { label: 'Génova' },
  { label: 'Gómez Plata' },
  { label: 'Güepsa' },
  { label: 'Güicán' },
  { label: 'Hacarí' },
  { label: 'Hatillo de Loba' },
  { label: 'Hato' },
  { label: 'Hato Corozal' },
  { label: 'Hatonuevo' },
  { label: 'Heliconia' },
  { label: 'Herrán' },
  { label: 'Herveo' },
  { label: 'Hispania' },
  { label: 'Hobo' },
  { label: 'Honda' },
  { label: 'Ibagué' },
  { label: 'Icononzo' },
  { label: 'Iles' },
  { label: 'Imués' },
  { label: 'Inzá' },
  { label: 'Inírida' },
  { label: 'Ipiales' },
  { label: 'Iquira' },
  { label: 'Isnos' },
  { label: 'Istmina' },
  { label: 'Itagüí' },
  { label: 'Ituango' },
  { label: 'Iza' },
  { label: 'Jambaló' },
  { label: 'Jamundí' },
  { label: 'Jardín' },
  { label: 'Jenesano' },
  { label: 'Jericó' },
  { label: 'Jerusalén' },
  { label: 'Jesús María' },
  { label: 'Jordán' },
  { label: 'Juan de Acosta' },
  { label: 'Junín' },
  { label: 'Juradó' },
  { label: 'La Apartada' },
  { label: 'La Argentina' },
  { label: 'La Belleza' },
  { label: 'La Calera' },
  { label: 'La Capilla' },
  { label: 'La Ceja' },
  { label: 'La Celia' },
  { label: 'La Chorrera' },
  { label: 'La Cruz' },
  { label: 'La Cumbre' },
  { label: 'La Dorada' },
  { label: 'La Esperanza' },
  { label: 'La Estrella' },
  { label: 'La Florida' },
  { label: 'La Gloria' },
  { label: 'La Guadalupe' },
  { label: 'La Jagua de Ibirico' },
  { label: 'La Jagua del Pilar' },
  { label: 'La Llanada' },
  { label: 'La Macarena' },
  { label: 'La Merced' },
  { label: 'La Mesa' },
  { label: 'La Montañita' },
  { label: 'La Palma' },
  { label: 'La Paz' },
  { label: 'La Pedrera' },
  { label: 'La Peña' },
  { label: 'La Pintada' },
  { label: 'La Plata' },
  { label: 'La Playa' },
  { label: 'La Primavera' },
  { label: 'La Salina' },
  { label: 'La Sierra' },
  { label: 'La Tebaida' },
  { label: 'La Tola' },
  { label: 'La Unión' },
  { label: 'La Uvita' },
  { label: 'La Vega' },
  { label: 'La Victoria' },
  { label: 'La Virginia' },
  { label: 'Labateca' },
  { label: 'Labranzagrande' },
  { label: 'Landázuri' },
  { label: 'Lebrija' },
  { label: 'Leguízamo' },
  { label: 'Leiva' },
  { label: 'Lejanías' },
  { label: 'Lenguazaque' },
  { label: 'Leticia' },
  { label: 'Liborina' },
  { label: 'Linares' },
  { label: 'Litoral de San Juan' },
  { label: 'Lloró' },
  { label: 'Los Andes' },
  { label: 'Los Córdobas' },
  { label: 'Los Palmitos' },
  { label: 'Los Patios' },
  { label: 'Los Santos' },
  { label: 'Lourdes' },
  { label: 'Luruaco' },
  { label: 'Lérida' },
  { label: 'Líbano' },
  { label: 'López' },
  { label: 'Macanal' },
  { label: 'Macaravita' },
  { label: 'Maceo' },
  { label: 'Macheta' },
  { label: 'Madrid' },
  { label: 'Magangué' },
  { label: 'Magüi' },
  { label: 'Mahates' },
  { label: 'Maicao' },
  { label: 'Majagual' },
  { label: 'Malambo' },
  { label: 'Mallama' },
  { label: 'Manatí' },
  { label: 'Manaure' },
  { label: 'Manizales' },
  { label: 'Manta' },
  { label: 'Manzanares' },
  { label: 'Maní' },
  { label: 'Mapiripana' },
  { label: 'Mapiripán' },
  { label: 'Margarita' },
  { label: 'Marinilla' },
  { label: 'Maripí' },
  { label: 'Mariquita' },
  { label: 'Marmato' },
  { label: 'Marquetalia' },
  { label: 'Marsella' },
  { label: 'Marulanda' },
  { label: 'María La Baja' },
  { label: 'Matanza' },
  { label: 'Medellín' },
  { label: 'Medina' },
  { label: 'Medio Atrato' },
  { label: 'Medio Baudó' },
  { label: 'Medio San Juan' },
  { label: 'Melgar' },
  { label: 'Mercaderes' },
  { label: 'Mesetas' },
  { label: 'Milán' },
  { label: 'Miraflores' },
  { label: 'Miranda' },
  { label: 'Miriti Paraná' },
  { label: 'Mistrató' },
  { label: 'Mitú' },
  { label: 'Mocoa' },
  { label: 'Mogotes' },
  { label: 'Molagavita' },
  { label: 'Momil' },
  { label: 'Mongua' },
  { label: 'Monguí' },
  { label: 'Moniquirá' },
  { label: 'Montebello' },
  { label: 'Montecristo' },
  { label: 'Montelíbano' },
  { label: 'Montenegro' },
  { label: 'Monterrey' },
  { label: 'Montería' },
  { label: 'Morales' },
  { label: 'Morelia' },
  { label: 'Morichal' },
  { label: 'Morroa' },
  { label: 'Mosquera' },
  { label: 'Motavita' },
  { label: 'Moñitos' },
  { label: 'Murillo' },
  { label: 'Murindó' },
  { label: 'Mutatá1' },
  { label: 'Mutiscua' },
  { label: 'Muzo' },
  { label: 'Málaga' },
  { label: 'Nariño' },
  { label: 'Natagaima' },
  { label: 'Nechí' },
  { label: 'Necoclí' },
  { label: 'Neira' },
  { label: 'Neiva' },
  { label: 'Nemocón' },
  { label: 'Nilo' },
  { label: 'Nimaima' },
  { label: 'Nobsa' },
  { label: 'Nocaima' },
  { label: 'Norcasia' },
  { label: 'Nueva Granada' },
  { label: 'Nuevo Colón' },
  { label: 'Nunchía' },
  { label: 'Nuquí' },
  { label: 'Nátaga' },
  { label: 'Nóvita' },
  { label: 'Obando' },
  { label: 'Ocamonte' },
  { label: 'Ocaña' },
  { label: 'Oiba' },
  { label: 'Oicatá' },
  { label: 'Olaya' },
  { label: 'Olaya Herrera' },
  { label: 'Onzaga' },
  { label: 'Oporapa' },
  { label: 'Orito' },
  { label: 'Orocué' },
  { label: 'Ortega' },
  { label: 'Ospina' },
  { label: 'Otanche' },
  { label: 'Ovejas' },
  { label: 'Pachavita' },
  { label: 'Pacho' },
  { label: 'Pacoa' },
  { label: 'Padilla' },
  { label: 'Paicol' },
  { label: 'Pailitas' },
  { label: 'Paime' },
  { label: 'Paipa' },
  { label: 'Pajarito' },
  { label: 'Palermo' },
  { label: 'Palestina' },
  { label: 'Palmar' },
  { label: 'Palmar de Varela' },
  { label: 'Palmas del Socorro' },
  { label: 'Palmira' },
  { label: 'Palmito' },
  { label: 'Palocabildo' },
  { label: 'Pamplona' },
  { label: 'Pamplonita' },
  { label: 'Pana Pana' },
  { label: 'Pandi' },
  { label: 'Panqueba' },
  { label: 'Papunaua' },
  { label: 'Paratebueno' },
  { label: 'Pasca' },
  { label: 'Patía' },
  { label: 'Pauna' },
  { label: 'Paya' },
  { label: 'Paz de Ariporo' },
  { label: 'Paz de Río' },
  { label: 'Pedraza' },
  { label: 'Pelaya' },
  { label: 'Pensilvania' },
  { label: 'Peque' },
  { label: 'Pereira' },
  { label: 'Pesca' },
  { label: 'Peñol' },
  { label: 'Piamonte' },
  { label: 'Piedecuesta' },
  { label: 'Piedras' },
  { label: 'Piendamó' },
  { label: 'Pijao' },
  { label: 'Pijiño del Carmen' },
  { label: 'Pinchote' },
  { label: 'Pinillos' },
  { label: 'Piojó' },
  { label: 'Pisba' },
  { label: 'Pitalito' },
  { label: 'Pivijay' },
  { label: 'Planadas' },
  { label: 'Planeta Rica' },
  { label: 'Plato' },
  { label: 'Policarpa' },
  { label: 'Polonuevo' },
  { label: 'Ponedera' },
  { label: 'Popayán' },
  { label: 'Pore' },
  { label: 'Potosí' },
  { label: 'Pradera' },
  { label: 'Prado' },
  { label: 'Providencia' },
  { label: 'Pueblo Bello' },
  { label: 'Pueblo Nuevo' },
  { label: 'Pueblo Rico' },
  { label: 'Pueblorrico' },
  { label: 'Puebloviejo' },
  { label: 'Puente Nacional' },
  { label: 'Puerres' },
  { label: 'Puerto Alegría' },
  { label: 'Puerto Arica' },
  { label: 'Puerto Asís' },
  { label: 'Puerto Berrío' },
  { label: 'Puerto Boyacá' },
  { label: 'Puerto Caicedo' },
  { label: 'Puerto Carreño' },
  { label: 'Puerto Colombia' },
  { label: 'Puerto Concordia' },
  { label: 'Puerto Escondido' },
  { label: 'Puerto Gaitán' },
  { label: 'Puerto Guzmán' },
  { label: 'Puerto Libertador' },
  { label: 'Puerto Lleras' },
  { label: 'Puerto López' },
  { label: 'Puerto Nare' },
  { label: 'Puerto Nariño' },
  { label: 'Puerto Parra' },
  { label: 'Puerto Rico' },
  { label: 'Puerto Rondón' },
  { label: 'Puerto Salgar' },
  { label: 'Puerto Santander' },
  { label: 'Puerto Tejada' },
  { label: 'Puerto Triunfo' },
  { label: 'Puerto Wilches' },
  { label: 'Pulí' },
  { label: 'Pupiales' },
  { label: 'Puracé' },
  { label: 'Purificación' },
  { label: 'Purísima' },
  { label: 'Pácora' },
  { label: 'Páez' },
  { label: 'Páramo' },
  { label: 'Quebradanegra' },
  { label: 'Quetame' },
  { label: 'Quibdó' },
  { label: 'Quimbaya' },
  { label: 'Quinchía' },
  { label: 'Quipile' },
  { label: 'Quípama' },
  { label: 'Ragonvalia' },
  { label: 'Ramiriquí' },
  { label: 'Recetor' },
  { label: 'Regidor' },
  { label: 'Remedios' },
  { label: 'Remolino' },
  { label: 'Repelón' },
  { label: 'Restrepo' },
  { label: 'Retiro' },
  { label: 'Ricaurte' },
  { label: 'Rioblanco' },
  { label: 'Riofrío' },
  { label: 'Riohacha' },
  { label: 'Rionegro' },
  { label: 'Riosucio' },
  { label: 'Riosucio1' },
  { label: 'Risaralda' },
  { label: 'Rivera' },
  { label: 'Roberto Payán' },
  { label: 'Roldanillo' },
  { label: 'Roncesvalles' },
  { label: 'Rondón' },
  { label: 'Rosas' },
  { label: 'Rovira' },
  { label: 'Ráquira' },
  { label: 'Río Iro' },
  { label: 'Río Quito' },
  { label: 'Río Viejo' },
  { label: 'Río de Oro' },
  { label: 'Sabana de Torres' },
  { label: 'Sabanagrande' },
  { label: 'Sabanalarga' },
  { label: 'Sabanas de San Angel' },
  { label: 'Sabaneta' },
  { label: 'Saboyá' },
  { label: 'Sahagún' },
  { label: 'Saladoblanco' },
  { label: 'Salamina' },
  { label: 'Salazar' },
  { label: 'Saldaña' },
  { label: 'Salento' },
  { label: 'Salgar' },
  { label: 'Samacá' },
  { label: 'Samaniego' },
  { label: 'Samaná' },
  { label: 'Sampués' },
  { label: 'San Agustín' },
  { label: 'San Alberto' },
  { label: 'San Andrés' },
  { label: 'San Andrés de Cuerquía' },
  { label: 'San Andrés de Sotavento' },
  { label: 'San Antero' },
  { label: 'San Antonio' },
  { label: 'San Antonio del Tequendama' },
  { label: 'San Benito' },
  { label: 'San Benito Abad' },
  { label: 'San Bernardo' },
  { label: 'San Bernardo del Viento' },
  { label: 'San Calixto' },
  { label: 'San Carlos' },
  { label: 'San Carlos de Guaroa' },
  { label: 'San Cayetano' },
  { label: 'San Cristóbal' },
  { label: 'San Diego' },
  { label: 'San Eduardo' },
  { label: 'San Estanislao' },
  { label: 'San Felipe' },
  { label: 'San Fernando' },
  { label: 'San Francisco' },
  { label: 'San Gil' },
  { label: 'San Jacinto' },
  { label: 'San Jacinto del Cauca' },
  { label: 'San Jerónimo' },
  { label: 'San Joaquín' },
  { label: 'San José' },
  { label: 'San José de La Montaña' },
  { label: 'San José de Miranda' },
  { label: 'San José de Pare' },
  { label: 'San José del Fragua' },
  { label: 'San José del Guaviare' },
  { label: 'San José del Palmar' },
  { label: 'San Juan Girón' },
  { label: 'San Juan Nepomuceno' },
  { label: 'San Juan de Arama' },
  { label: 'San Juan de Betulia' },
  { label: 'San Juan de Pasto' },
  { label: 'San Juan de Río Seco' },
  { label: 'San Juan de Urabá' },
  { label: 'San Juan del Cesar' },
  { label: 'San Juanito' },
  { label: 'San Lorenzo' },
  { label: 'San Luis' },
  { label: 'San Luis de Gaceno' },
  { label: 'San Luis de Palenque' },
  { label: 'San Luis de Sincé' },
  { label: 'San Marcos' },
  { label: 'San Martín' },
  { label: 'San Martín de Loba' },
  { label: 'San Mateo' },
  { label: 'San Miguel' },
  { label: 'San Miguel de Sema' },
  { label: 'San Onofre' },
  { label: 'San Pablo' },
  { label: 'San Pablo de Borbur' },
  { label: 'San Pedro' },
  { label: 'San Pedro de Cartago' },
  { label: 'San Pedro de Urabá' },
  { label: 'San Pelayo' },
  { label: 'San Rafael' },
  { label: 'San Roque' },
  { label: 'San Sebastián' },
  { label: 'San Sebastián de Buenavista' },
  { label: 'San Vicente' },
  { label: 'San Vicente de Chucurí' },
  { label: 'San Vicente del Caguán' },
  { label: 'San Zenón' },
  { label: 'Sandoná' },
  { label: 'Santa Ana' },
  { label: 'Santa Bárbara' },
  { label: 'Santa Bárbara de Pinto' },
  { label: 'Santa Catalina' },
  { label: 'Santa Cruz de Lorica' },
  { label: 'Santa Cruz de Mompox' },
  { label: 'Santa Fe de Antioquia' },
  { label: 'Santa Helena del Opón' },
  { label: 'Santa Isabel' },
  { label: 'Santa Lucía' },
  { label: 'Santa Marta' },
  { label: 'Santa María' },
  { label: 'Santa Rosa' },
  { label: 'Santa Rosa de Cabal' },
  { label: 'Santa Rosa de Osos' },
  { label: 'Santa Rosa de Viterbo' },
  { label: 'Santa Rosa del Sur' },
  { label: 'Santa Rosalía' },
  { label: 'Santa Sofía' },
  { label: 'Santacruz' },
  { label: 'Santana' },
  { label: 'Santander de Quilichao' },
  { label: 'Santiago' },
  { label: 'Santo Domingo' },
  { label: 'Santo Tomás' },
  { label: 'Santuario' },
  { label: 'Sapuyes' },
  { label: 'Saravena' },
  { label: 'Sardinata' },
  { label: 'Sasaima' },
  { label: 'Sativanorte' },
  { label: 'Sativasur' },
  { label: 'Segovia' },
  { label: 'Sesquilé' },
  { label: 'Sevilla' },
  { label: 'Siachoque' },
  { label: 'Sibaté' },
  { label: 'Sibundoy' },
  { label: 'Silos' },
  { label: 'Silvania' },
  { label: 'Silvia' },
  { label: 'Simacota' },
  { label: 'Simijaca' },
  { label: 'Simití' },
  { label: 'Sincelejo' },
  { label: 'Sipí' },
  { label: 'Sitionuevo' },
  { label: 'Soacha' },
  { label: 'Soatá' },
  { label: 'Socha' },
  { label: 'Socorro' },
  { label: 'Socotá' },
  { label: 'Sogamoso' },
  { label: 'Solano' },
  { label: 'Soledad' },
  { label: 'Solita' },
  { label: 'Somondoco' },
  { label: 'Sonsón' },
  { label: 'Sopetrán' },
  { label: 'Soplaviento' },
  { label: 'Sopó' },
  { label: 'Sora' },
  { label: 'Soracá' },
  { label: 'Sotaquirá' },
  { label: 'Sotara' },
  { label: 'Suaita' },
  { label: 'Suan' },
  { label: 'Suaza' },
  { label: 'Subachoque' },
  { label: 'Sucre' },
  { label: 'Suesca' },
  { label: 'Supatá' },
  { label: 'Supía' },
  { label: 'Suratá' },
  { label: 'Susa' },
  { label: 'Susacón' },
  { label: 'Sutamarchán' },
  { label: 'Sutatausa' },
  { label: 'Sutatenza' },
  { label: 'Suárez' },
  { label: 'Sácama' },
  { label: 'Sáchica' },
  { label: 'Tabio' },
  { label: 'Tadó' },
  { label: 'Talaigua Nuevo' },
  { label: 'Tamalameque' },
  { label: 'Tame' },
  { label: 'Taminango' },
  { label: 'Tangua' },
  { label: 'Taraira' },
  { label: 'Tarapacá' },
  { label: 'Tarazá' },
  { label: 'Tarqui' },
  { label: 'Tarso' },
  { label: 'Tasco' },
  { label: 'Tauramena' },
  { label: 'Tausa' },
  { label: 'Tello' },
  { label: 'Tena' },
  { label: 'Tenerife' },
  { label: 'Tenjo' },
  { label: 'Tenza' },
  { label: 'Teorama' },
  { label: 'Teruel' },
  { label: 'Tesalia' },
  { label: 'Tibacuy' },
  { label: 'Tibaná' },
  { label: 'Tibasosa' },
  { label: 'Tibirita' },
  { label: 'Tibú' },
  { label: 'Tierralta' },
  { label: 'Timaná' },
  { label: 'Timbiquí' },
  { label: 'Timbío' },
  { label: 'Tinjacá' },
  { label: 'Tipacoque' },
  { label: 'Tiquisio' },
  { label: 'Titiribí' },
  { label: 'Toca' },
  { label: 'Tocaima' },
  { label: 'Tocancipá' },
  { label: 'Togüí' },
  { label: 'Toledo' },
  { label: 'Tolú' },
  { label: 'Tolú Viejo' },
  { label: 'Tona' },
  { label: 'Topaipí' },
  { label: 'Toribio' },
  { label: 'Toro' },
  { label: 'Tota' },
  { label: 'Totoró' },
  { label: 'Trinidad' },
  { label: 'Trujillo' },
  { label: 'Tubará' },
  { label: 'Tuluá' },
  { label: 'Tumaco' },
  { label: 'Tunja' },
  { label: 'Tununguá' },
  { label: 'Turbaco' },
  { label: 'Turbaná' },
  { label: 'Turbo' },
  { label: 'Turmequé' },
  { label: 'Tuta' },
  { label: 'Tutazá' },
  { label: 'Támara' },
  { label: 'Támesis' },
  { label: 'Tópaga' },
  { label: 'Túquerres' },
  { label: 'Ubalá' },
  { label: 'Ubaque' },
  { label: 'Ubaté' },
  { label: 'Ulloa' },
  { label: 'Umbita' },
  { label: 'Une' },
  { label: 'Unguía' },
  { label: 'Unión Panamericana' },
  { label: 'Uramita' },
  { label: 'Uribe' },
  { label: 'Uribia' },
  { label: 'Urrao' },
  { label: 'Urumita' },
  { label: 'Usiacurí' },
  { label: 'Valdivia' },
  { label: 'Valencia' },
  { label: 'Valle de San José' },
  { label: 'Valle de San Juan' },
  { label: 'Valle del Guamuez' },
  { label: 'Valledupar' },
  { label: 'Valparaíso' },
  { label: 'Vegachí' },
  { label: 'Venadillo' },
  { label: 'Venecia' },
  { label: 'Ventaquemada' },
  { label: 'Vergara' },
  { label: 'Versalles' },
  { label: 'Vetas' },
  { label: 'Vianí' },
  { label: 'Victoria' },
  { label: 'Vigía del Fuerte' },
  { label: 'Vijes' },
  { label: 'Villa Caro' },
  { label: 'Villa Rica' },
  { label: 'Villa de Leyva' },
  { label: 'Villa del Rosario' },
  { label: 'Villagarzón' },
  { label: 'Villagómez' },
  { label: 'Villahermosa' },
  { label: 'Villamaría' },
  { label: 'Villanueva' },
  { label: 'Villapinzón' },
  { label: 'Villarrica' },
  { label: 'Villavicencio' },
  { label: 'Villavieja' },
  { label: 'Villeta' },
  { label: 'Viotá' },
  { label: 'Viracachá' },
  { label: 'Vista Hermosa' },
  { label: 'Viterbo' },
  { label: 'Vélez' },
  { label: 'Yacopí' },
  { label: 'Yacuanquer' },
  { label: 'Yaguará' },
  { label: 'Yalí' },
  { label: 'Yarumal' },
  { label: 'Yavaraté' },
  { label: 'Yolombó' },
  { label: 'Yondó' },
  { label: 'Yopal' },
  { label: 'Yotoco' },
  { label: 'Yumbo' },
  { label: 'Zambrano' },
  { label: 'Zapatoca' },
  { label: 'Zapayán' },
  { label: 'Zaragoza' },
  { label: 'Zarzal' },
  { label: 'Zetaquira' },
  { label: 'Zipacón' },
  { label: 'Zipaquirá' },
  { label: 'Zona Bananera' },
  { label: 'Útica' },
]

cityOptions = cityOptions.map((city) => {
  return { label: city.label, value: city.label }
})

export default cityOptions
