let countryOptions = [
  { label: 'Afganistán' },
  { label: 'Åland' },
  { label: 'Albania' },
  { label: 'Alemania' },
  { label: 'Andorra' },
  { label: 'Angola' },
  { label: 'Anguila' },
  { label: 'Antártida' },
  { label: 'Antigua y Barbuda' },
  { label: 'Antillas Neerlandesas' },
  { label: 'Arabia Saudita' },
  { label: 'Argelia' },
  { label: 'Argentina' },
  { label: 'Armenia' },
  { label: 'Aruba' },
  { label: 'Australia' },
  { label: 'Austria' },
  { label: 'Azerbaiyán' },
  { label: 'Bahamas' },
  { label: 'Bahréin' },
  { label: 'Bangladesh' },
  { label: 'Barbados' },
  { label: 'Bélgica' },
  { label: 'Belice' },
  { label: 'Benín' },
  { label: 'Bermudas' },
  { label: 'Bielorrusia' },
  { label: 'Birmania' },
  { label: 'Bolivia' },
  { label: 'Bosnia y Herzegovina' },
  { label: 'Botsuana' },
  { label: 'Isla Bouvet' },
  { label: 'Brasil' },
  { label: 'Brunéi' },
  { label: 'Bulgaria' },
  { label: 'Burkina Faso' },
  { label: 'Burundi' },
  { label: 'Bután' },
  { label: 'Cabo Verde' },
  { label: 'Islas Caimán' },
  { label: 'Camboya' },
  { label: 'Camerún' },
  { label: 'Canadá' },
  { label: 'República Centroafricana' },
  { label: 'Chad' },
  { label: 'República Checa' },
  { label: 'Chile' },
  { label: 'China' },
  { label: 'Chipre' },
  { label: 'Islas Cocos' },
  { label: 'Colombia' },
  { label: 'Comoras' },
  { label: 'República del Congo' },
  { label: 'República Democrática del Congo' },
  { label: 'Islas Cook' },
  { label: 'Corea del Norte' },
  { label: 'Corea del Sur' },
  { label: 'Costa de Marfil' },
  { label: 'Costa Rica' },
  { label: 'Croacia' },
  { label: 'Cuba' },
  { label: 'Dinamarca' },
  { label: 'Dominica' },
  { label: 'República Dominicana' },
  { label: 'Ecuador' },
  { label: 'Egipto' },
  { label: 'El Salvador' },
  { label: 'Emiratos Árabes Unidos' },
  { label: 'Eritrea' },
  { label: 'Eslovaquia' },
  { label: 'Eslovenia' },
  { label: 'España' },
  { label: 'Estados Unidos' },
  { label: 'Islas ultramarinas de Estados Unidos' },
  { label: 'Estonia' },
  { label: 'Etiopía' },
  { label: 'Islas Feroe' },
  { label: 'Filipinas' },
  { label: 'Finlandia' },
  { label: 'Fiyi' },
  { label: 'Francia' },
  { label: 'Gabón' },
  { label: 'Gambia' },
  { label: 'Georgia' },
  { label: 'Islas Georgias del Sur y Sandwich del Sur' },
  { label: 'Ghana' },
  { label: 'Gibraltar' },
  { label: 'Granada' },
  { label: 'Grecia' },
  { label: 'Groenlandia' },
  { label: 'Guadalupe' },
  { label: 'Guam' },
  { label: 'Guatemala' },
  { label: 'Guayana Francesa' },
  { label: 'Guernsey' },
  { label: 'Guinea' },
  { label: 'Guinea Ecuatorial' },
  { label: 'Guinea-Bissau' },
  { label: 'Guyana' },
  { label: 'Haití' },
  { label: 'Islas Heard y McDonald' },
  { label: 'Honduras' },
  { label: 'Hong Kong' },
  { label: 'Hungría' },
  { label: 'India' },
  { label: 'Indonesia' },
  { label: 'Irán' },
  { label: 'Iraq' },
  { label: 'Irlanda' },
  { label: 'Islandia' },
  { label: 'Israel' },
  { label: 'Italia' },
  { label: 'Jamaica' },
  { label: 'Japón' },
  { label: 'Jersey' },
  { label: 'Jordania' },
  { label: 'Kazajistán' },
  { label: 'Kenia' },
  { label: 'Kirguistán' },
  { label: 'Kiribati' },
  { label: 'Kuwait' },
  { label: 'Laos' },
  { label: 'Lesoto' },
  { label: 'Letonia' },
  { label: 'Líbano' },
  { label: 'Liberia' },
  { label: 'Libia' },
  { label: 'Liechtenstein' },
  { label: 'Lituania' },
  { label: 'Luxemburgo' },
  { label: 'Macao' },
  { label: 'República de Macedonia' },
  { label: 'Madagascar' },
  { label: 'Malasia' },
  { label: 'Malaui' },
  { label: 'Maldivas' },
  { label: 'Malí' },
  { label: 'Malta' },
  { label: 'Islas Malvinas' },
  { label: 'Isla de Man' },
  { label: 'Islas Marianas del Norte' },
  { label: 'Marruecos' },
  { label: 'Islas Marshall' },
  { label: 'Martinica' },
  { label: 'Mauricio' },
  { label: 'Mauritania' },
  { label: 'Mayotte' },
  { label: 'México' },
  { label: 'Micronesia' },
  { label: 'Moldavia' },
  { label: 'Mónaco' },
  { label: 'Mongolia' },
  { label: 'Montenegro' },
  { label: 'Montserrat' },
  { label: 'Mozambique' },
  { label: 'Namibia' },
  { label: 'Nauru' },
  { label: 'Isla de Navidad' },
  { label: 'Nepal' },
  { label: 'Nicaragua' },
  { label: 'Níger' },
  { label: 'Nigeria' },
  { label: 'Niue' },
  { label: 'Norfolk' },
  { label: 'Noruega' },
  { label: 'Nueva Caledonia' },
  { label: 'Nueva Zelanda' },
  { label: 'Omán' },
  { label: 'Países Bajos' },
  { label: 'Pakistán' },
  { label: 'Palaos' },
  { label: 'Territorios palestinos' },
  { label: 'Panamá' },
  { label: 'Papúa Nueva Guinea' },
  { label: 'Paraguay' },
  { label: 'Perú' },
  { label: 'Islas Pitcairn' },
  { label: 'Polinesia Francesa' },
  { label: 'Polonia' },
  { label: 'Portugal' },
  { label: 'Puerto Rico' },
  { label: 'Qatar' },
  { label: 'Reino Unido' },
  { label: 'Reunión' },
  { label: 'Ruanda' },
  { label: 'Rumania' },
  { label: 'Rusia' },
  { label: 'República Árabe Saharaui Democrática' },
  { label: 'Islas Salomón' },
  { label: 'Samoa' },
  { label: 'Samoa Americana' },
  { label: 'San Bartolomé' },
  { label: 'San Cristóbal y Nieves' },
  { label: 'San Marino' },
  { label: 'San Martín' },
  { label: 'San Pedro y Miquelón' },
  { label: 'San Vicente y las Granadinas' },
  { label: 'Santa Helena' },
  { label: 'Santa Lucía' },
  { label: 'Santo Tomé y Príncipe' },
  { label: 'Senegal' },
  { label: 'Serbia' },
  { label: 'Seychelles' },
  { label: 'Sierra Leona' },
  { label: 'Singapur' },
  { label: 'Siria' },
  { label: 'Somalia' },
  { label: 'Sri Lanka' },
  { label: 'Suazilandia' },
  { label: 'Sudáfrica' },
  { label: 'Sudán' },
  { label: 'Suecia' },
  { label: 'Suiza' },
  { label: 'Surinam' },
  { label: 'Svalbard y Jan Mayen' },
  { label: 'Tailandia' },
  { label: 'Taiwán' },
  { label: 'Tanzania' },
  { label: 'Tayikistán' },
  { label: 'Territorio Británico del Océano Índico' },
  { label: 'Territorios Australes Franceses' },
  { label: 'Timor Oriental' },
  { label: 'Togo' },
  { label: 'Tokelau' },
  { label: 'Tonga' },
  { label: 'Trinidad y Tobago' },
  { label: 'Túnez' },
  { label: 'Islas Turcas y Caicos' },
  { label: 'Turkmenistán' },
  { label: 'Turquía' },
  { label: 'Tuvalu' },
  { label: 'Ucrania' },
  { label: 'Uganda' },
]

countryOptions = countryOptions.map((country) => {
  return { label: country.label, value: country.label }
})

export default countryOptions
