let indicativeCountryOptions = [
  { label: '+57 - Colombia 🇨🇴' },
  { label: '+93 - Afghanistan 🇦🇫' },
  { label: '+358 - Finland 🇫🇮' },
  { label: '+355 - Albania 🇦🇱' },
  { label: '+213 - Algeria 🇩🇿' },
  { label: '+1684 - AmericanSamoa 🇦🇸' },
  { label: '+376 - Andorra 🇦🇩' },
  { label: '+244 - Angola 🇦🇴' },
  { label: '+1264 - Anguilla 🇦🇮' },
  { label: '+672 - Norfolk Island 🇳🇫' },
  { label: '+1268 - Antigua and Barbuda 🇦🇬' },
  { label: '+54 - Argentina 🇦🇷' },
  { label: '+374 - Armenia 🇦🇲' },
  { label: '+297 - Aruba 🇦🇼' },
  { label: '+61 - Cocos (Keeling) Islands 🇨🇨' },
  { label: '+43 - Austria 🇦🇹' },
  { label: '+994 - Azerbaijan 🇦🇿' },
  { label: '+1242 - Bahamas 🇧🇸' },
  { label: '+973 - Bahrain 🇧🇭' },
  { label: '+880 - Bangladesh 🇧🇩' },
  { label: '+1246 - Barbados 🇧🇧' },
  { label: '+375 - Belarus 🇧🇾' },
  { label: '+32 - Belgium 🇧🇪' },
  { label: '+501 - Belize 🇧🇿' },
  { label: '+229 - Benin 🇧🇯' },
  { label: '+1441 - Bermuda 🇧🇲' },
  { label: '+975 - Bhutan 🇧🇹' },
  { label: '+591 - Bolivia, Plurinational State of 🇧🇴' },
  { label: '+387 - Bosnia and Herzegovina 🇧🇦' },
  { label: '+267 - Botswana 🇧🇼' },
  { label: '+55 - Brazil 🇧🇷' },
  { label: '+246 - British Indian Ocean Territory 🇮🇴' },
  { label: '+673 - Brunei Darussalam 🇧🇳' },
  { label: '+359 - Bulgaria 🇧🇬' },
  { label: '+226 - Burkina Faso 🇧🇫' },
  { label: '+257 - Burundi 🇧🇮' },
  { label: '+855 - Cambodia 🇰🇭' },
  { label: '+237 - Cameroon 🇨🇲' },
  { label: '+1 - United States 🇺🇸' },
  { label: '+238 - Cape Verde 🇨🇻' },
  { label: '+ 345 - Cayman Islands 🇰🇾' },
  { label: '+236 - Central African Republic 🇨🇫' },
  { label: '+235 - Chad 🇹🇩' },
  { label: '+56 - Chile 🇨🇱' },
  { label: '+86 - China 🇨🇳' },
  { label: '+269 - Comoros 🇰🇲' },
  { label: '+242 - Congo 🇨🇬' },
  { label: '+243 - Congo, The Democratic Republic of the Congo 🇨🇩' },
  { label: '+682 - Cook Islands 🇨🇰' },
  { label: '+506 - Costa Rica 🇨🇷' },
  { label: '+225 - Cote dIvoire 🇨🇮' },
  { label: '+385 - Croatia 🇭🇷' },
  { label: '+53 - Cuba 🇨🇺' },
  { label: '+357 - Cyprus 🇨🇾' },
  { label: '+420 - Czech Republic 🇨🇿' },
  { label: '+45 - Denmark 🇩🇰' },
  { label: '+253 - Djibouti 🇩🇯' },
  { label: '+1767 - Dominica 🇩🇲' },
  { label: '+1849 - Dominican Republic 🇩🇴' },
  { label: '+593 - Ecuador 🇪🇨' },
  { label: '+20 - Egypt 🇪🇬' },
  { label: '+503 - El Salvador 🇸🇻' },
  { label: '+240 - Equatorial Guinea 🇬🇶' },
  { label: '+291 - Eritrea 🇪🇷' },
  { label: '+372 - Estonia 🇪🇪' },
  { label: '+251 - Ethiopia 🇪🇹' },
  { label: '+500 - South Georgia and the South Sandwich Islands 🇬🇸' },
  { label: '+298 - Faroe Islands 🇫🇴' },
  { label: '+679 - Fiji 🇫🇯' },
  { label: '+33 - France 🇫🇷' },
  { label: '+594 - French Guiana 🇬🇫' },
  { label: '+689 - French Polynesia 🇵🇫' },
  { label: '+241 - Gabon 🇬🇦' },
  { label: '+220 - Gambia 🇬🇲' },
  { label: '+995 - Georgia 🇬🇪' },
  { label: '+49 - Germany 🇩🇪' },
  { label: '+233 - Ghana 🇬🇭' },
  { label: '+350 - Gibraltar 🇬🇮' },
  { label: '+30 - Greece 🇬🇷' },
  { label: '+299 - Greenland 🇬🇱' },
  { label: '+1473 - Grenada 🇬🇩' },
  { label: '+590 - Saint Martin 🇲🇫' },
  { label: '+1671 - Guam 🇬🇺' },
  { label: '+502 - Guatemala 🇬🇹' },
  { label: '+44 - United Kingdom 🇬🇧' },
  { label: '+224 - Guinea 🇬🇳' },
  { label: '+245 - Guinea-Bissau 🇬🇼' },
  { label: '+595 - Paraguay 🇵🇾' },
  { label: '+509 - Haiti 🇭🇹' },
  { label: '+379 - Holy See (Vatican City State) 🇻🇦' },
  { label: '+504 - Honduras 🇭🇳' },
  { label: '+852 - Hong Kong 🇭🇰' },
  { label: '+36 - Hungary 🇭🇺' },
  { label: '+354 - Iceland 🇮🇸' },
  { label: '+91 - India 🇮🇳' },
  { label: '+62 - Indonesia 🇮🇩' },
  { label: '+98 - Iran, Islamic Republic of Persian Gulf 🇮🇷' },
  { label: '+964 - Iraq 🇮🇶' },
  { label: '+353 - Ireland 🇮🇪' },
  { label: '+972 - Israel 🇮🇱' },
  { label: '+39 - Italy 🇮🇹' },
  { label: '+1876 - Jamaica 🇯🇲' },
  { label: '+81 - Japan 🇯🇵' },
  { label: '+962 - Jordan 🇯🇴' },
  { label: '+77 - Kazakhstan 🇰🇿' },
  { label: '+254 - Kenya 🇰🇪' },
  { label: '+686 - Kiribati 🇰🇮' },
  { label: '+850 - Korea, Democratic Peoples Republic of Korea 🇰🇵' },
  { label: '+82 - Korea, Republic of South Korea 🇰🇷' },
  { label: '+965 - Kuwait 🇰🇼' },
  { label: '+996 - Kyrgyzstan 🇰🇬' },
  { label: '+856 - Laos 🇱🇦' },
  { label: '+371 - Latvia 🇱🇻' },
  { label: '+961 - Lebanon 🇱🇧' },
  { label: '+266 - Lesotho 🇱🇸' },
  { label: '+231 - Liberia 🇱🇷' },
  { label: '+218 - Libyan Arab Jamahiriya 🇱🇾' },
  { label: '+423 - Liechtenstein 🇱🇮' },
  { label: '+370 - Lithuania 🇱🇹' },
  { label: '+352 - Luxembourg 🇱🇺' },
  { label: '+853 - Macao 🇲🇴' },
  { label: '+389 - Macedonia 🇲🇰' },
  { label: '+261 - Madagascar 🇲🇬' },
  { label: '+265 - Malawi 🇲🇼' },
  { label: '+60 - Malaysia 🇲🇾' },
  { label: '+960 - Maldives 🇲🇻' },
  { label: '+223 - Mali 🇲🇱' },
  { label: '+356 - Malta 🇲🇹' },
  { label: '+692 - Marshall Islands 🇲🇭' },
  { label: '+596 - Martinique 🇲🇶' },
  { label: '+222 - Mauritania 🇲🇷' },
  { label: '+230 - Mauritius 🇲🇺' },
  { label: '+262 - Reunion 🇷🇪' },
  { label: '+52 - Mexico 🇲🇽' },
  { label: '+691 - Micronesia, Federated States of Micronesia 🇫🇲' },
  { label: '+373 - Moldova 🇲🇩' },
  { label: '+377 - Monaco 🇲🇨' },
  { label: '+976 - Mongolia 🇲🇳' },
  { label: '+382 - Montenegro 🇲🇪' },
  { label: '+1664 - Montserrat 🇲🇸' },
  { label: '+212 - Morocco 🇲🇦' },
  { label: '+258 - Mozambique 🇲🇿' },
  { label: '+95 - Myanmar 🇲🇲' },
  { label: '+264 - Namibia 🇳🇦' },
  { label: '+674 - Nauru 🇳🇷' },
  { label: '+977 - Nepal 🇳🇵' },
  { label: '+31 - Netherlands 🇳🇱' },
  { label: '+687 - New Caledonia 🇳🇨' },
  { label: '+64 - New Zealand 🇳🇿' },
  { label: '+505 - Nicaragua 🇳🇮' },
  { label: '+227 - Niger 🇳🇪' },
  { label: '+234 - Nigeria 🇳🇬' },
  { label: '+683 - Niue 🇳🇺' },
  { label: '+1670 - Northern Mariana Islands 🇲🇵' },
  { label: '+47 - Svalbard and Jan Mayen 🇸🇯' },
  { label: '+968 - Oman 🇴🇲' },
  { label: '+92 - Pakistan 🇵🇰' },
  { label: '+680 - Palau 🇵🇼' },
  { label: '+970 - Palestinian Territory, Occupied 🇵🇸' },
  { label: '+507 - Panama 🇵🇦' },
  { label: '+675 - Papua New Guinea 🇵🇬' },
  { label: '+51 - Peru 🇵🇪' },
  { label: '+63 - Philippines 🇵🇭' },
  { label: '+872 - Pitcairn 🇵🇳' },
  { label: '+48 - Poland 🇵🇱' },
  { label: '+351 - Portugal 🇵🇹' },
  { label: '+1939 - Puerto Rico 🇵🇷' },
  { label: '+974 - Qatar 🇶🇦' },
  { label: '+40 - Romania 🇷🇴' },
  { label: '+7 - Russia 🇷🇺' },
  { label: '+250 - Rwanda 🇷🇼' },
  { label: '+290 - Saint Helena, Ascension and Tristan Da Cunha 🇸🇭' },
  { label: '+1869 - Saint Kitts and Nevis 🇰🇳' },
  { label: '+1758 - Saint Lucia 🇱🇨' },
  { label: '+508 - Saint Pierre and Miquelon 🇵🇲' },
  { label: '+1784 - Saint Vincent and the Grenadines 🇻🇨' },
  { label: '+685 - Samoa 🇼🇸' },
  { label: '+378 - San Marino 🇸🇲' },
  { label: '+239 - Sao Tome and Principe 🇸🇹' },
  { label: '+966 - Saudi Arabia 🇸🇦' },
  { label: '+221 - Senegal 🇸🇳' },
  { label: '+381 - Serbia 🇷🇸' },
  { label: '+248 - Seychelles 🇸🇨' },
  { label: '+232 - Sierra Leone 🇸🇱' },
  { label: '+65 - Singapore 🇸🇬' },
  { label: '+421 - Slovakia 🇸🇰' },
  { label: '+386 - Slovenia 🇸🇮' },
  { label: '+677 - Solomon Islands 🇸🇧' },
  { label: '+252 - Somalia 🇸🇴' },
  { label: '+27 - South Africa 🇿🇦' },
  { label: '+211 - South Sudan 🇸🇸' },
  { label: '+34 - Spain 🇪🇸' },
  { label: '+94 - Sri Lanka 🇱🇰' },
  { label: '+249 - Sudan 🇸🇩' },
  { label: '+597 - Suriname 🇸🇷' },
  { label: '+268 - Swaziland 🇸🇿' },
  { label: '+46 - Sweden 🇸🇪' },
  { label: '+41 - Switzerland 🇨🇭' },
  { label: '+963 - Syrian Arab Republic 🇸🇾' },
  { label: '+886 - Taiwan 🇹🇼' },
  { label: '+992 - Tajikistan 🇹🇯' },
  { label: '+255 - Tanzania, United Republic of Tanzania 🇹🇿' },
  { label: '+66 - Thailand 🇹🇭' },
  { label: '+670 - Timor-Leste 🇹🇱' },
  { label: '+228 - Togo 🇹🇬' },
  { label: '+690 - Tokelau 🇹🇰' },
  { label: '+676 - Tonga 🇹🇴' },
  { label: '+1868 - Trinidad and Tobago 🇹🇹' },
  { label: '+216 - Tunisia 🇹🇳' },
  { label: '+90 - Turkey 🇹🇷' },
  { label: '+993 - Turkmenistan 🇹🇲' },
  { label: '+1649 - Turks and Caicos Islands 🇹🇨' },
  { label: '+688 - Tuvalu 🇹🇻' },
  { label: '+256 - Uganda 🇺🇬' },
  { label: '+380 - Ukraine 🇺🇦' },
  { label: '+971 - United Arab Emirates 🇦🇪' },
  { label: '+598 - Uruguay 🇺🇾' },
  { label: '+998 - Uzbekistan 🇺🇿' },
  { label: '+678 - Vanuatu 🇻🇺' },
  { label: '+58 - Venezuela, Bolivarian Republic of Venezuela 🇻🇪' },
  { label: '+84 - Vietnam 🇻🇳' },
  { label: '+1284 - Virgin Islands, British 🇻🇬' },
  { label: '+1340 - Virgin Islands, U.S. 🇻🇮' },
  { label: '+681 - Wallis and Futuna 🇼🇫' },
  { label: '+967 - Yemen 🇾🇪' },
  { label: '+260 - Zambia 🇿🇲' },
  { label: '+263 - Zimbabwe 🇿🇼' },
]

indicativeCountryOptions = indicativeCountryOptions.map((indicativeCountry) => {
  return { label: indicativeCountry.label, value: indicativeCountry.label }
})

export default indicativeCountryOptions
