import { useContext } from 'react';
import MillonaireCMSContext from '../contexts/MillonaireCMSContext';
export const useMillonaireCMS = () => {
  const {
    event,
    millonaire,
    loading,
    isNewGame,
    question,
    answer,
    stage,
    isVisibleModalQuestion,
    isVisibleModalStage,
    isEditStage,
    isEditAnswer,
    isEditQuestion,
    onChangeAppearance,
    onChangeMillonaire,
    onSubmit,
    onDelete,
    onSaveQuestion,
    onSaveStage,
    onCancelModalStage,
    onCancelModalQuestion,
    setIsVisibleModalQuestion,
    setIsVisibleModalStage,
    onChangeQuestion,
    onSaveAnswerInQuestion,
    onChangeAnswer,
    onChangeStage,
    onDeleteQuestion,
    onDeleteStage,
    onActionEditQuestion,
    onActionEditAnwser,
    onSubmitAnswer,
    onSubmitStage,
    onSubmitQuestion,
  } = useContext(MillonaireCMSContext);

  return {
    event,
    loading,
    millonaire,
    isNewGame,
    stage,
    question,
    answer,
    isVisibleModalQuestion,
    isVisibleModalStage,
    isEditStage,
    isEditAnswer,
    isEditQuestion,
    onChangeMillonaire,
    onChangeAppearance,
    onSubmit,
    onDelete,
    onSaveQuestion,
    onSaveStage,
    onChangeStage,
    onCancelModalStage,
    onCancelModalQuestion,
    setIsVisibleModalQuestion,
    setIsVisibleModalStage,
    onChangeQuestion,
    onSaveAnswerInQuestion,
    onChangeAnswer,
    onDeleteQuestion,
    onDeleteStage,
    onActionEditQuestion,
    onActionEditAnwser,
    onSubmitAnswer,
    onSubmitStage,
    onSubmitQuestion,
  };
};
