import { useContext } from 'react';
import MillonaireLandingContext from '../contexts/MillonaireLandingContext';
export const useMillonaireLanding = () => {
  const {
    event,
    millonaire,
    stages,
    loading,
    isVisible,
    startGame,
    currentStage,
    score,
    time,
    statusGame,
    question,
    stage,
    visibilityControl,
    scoreUser,
    scores,
    usedWildCards,
    onChangeVisibilityDrawer,
    onFinishedGame,
    onStartGame,
    onFiftyOverFifty,
    onSaveAnswer,
    onAnnouncement,
    onChangeStatusGame,
  } = useContext(MillonaireLandingContext);

  return {
    event,
    loading,
    millonaire,
    isVisible,
    stages,
    startGame,
    currentStage,
    score,
    time,
    statusGame,
    question,
    stage,
    visibilityControl,
    scoreUser,
    scores,
    usedWildCards,
    onChangeVisibilityDrawer,
    onStartGame,
    onFinishedGame,
    onFiftyOverFifty,
    onSaveAnswer,
    onAnnouncement,
    onChangeStatusGame,
  };
};
